const team_choice = document.getElementById("team_choice");
const story_node = document.getElementById("story")
const story = document.getElementById("story_choice");
const player_choice = document.getElementById("player_choice");
var team_full_name;
var full_name;
var story_choice;

async function checkURL(){
    const urlParams = new URLSearchParams(window.location.search);
    let team_selection = urlParams.get("team_choice");
    if(team_selection != null){
        team_choice.value = team_selection;
        team_full_name = team_choice.options[team_choice.selectedIndex].text;
        await fillPlayerChoice(parseInt(team_choice.value));
        let player_selection = urlParams.get("player_choice");
        console.log(player_selection);
        player_choice.value = player_selection;
        full_name = player_choice.options[player_choice.selectedIndex].text;
        let story_selection = urlParams.get("story_choice");
        story.value = story_selection;
        onStoryChange();
    }
}

async function getRosters() {
    const response = await fetch("https://raw.githubusercontent.com/jamesohara08/SpringTrainingStoryCreator/refs/heads/master/team_rosters.json");
    const data = await response.json();
    return data;
}

async function fillPlayerChoice(team_index){
    var team_rosters = await getRosters();
    var player_list = team_rosters[team_index];
    while(player_choice.firstChild){
        player_choice.removeChild(player_choice.firstChild);
    }
    const blankOption = document.createElement("option");
    blankOption.value = "";
    blankOption.text = "Select a Player";
    blankOption.disabled = true;
    blankOption.selected = true;
    player_choice.add(blankOption);
    player_list.forEach(player => {
        const newOption = document.createElement("option");
        newOption.value = player;
        newOption.text = player;
        player_choice.add(newOption);
    })
}

function buildStory(story_number, team_full_name, full_name){
    const team_nickname = team_full_name.split(" ")[1];
    const last_name = full_name.split(' ')[1];
    const story_1 = `<div id="story_content"><h1>Despite lackluster stats ${last_name} makes things happen</h1><p>While many will be paying attention to the big stars as Spring Training begins, perhaps the most important player on the ${team_full_name} will go overlooked. He may not hit tape measure home runs or impress anyone with his arm, but his hustle cannot be understated. </p><p>${full_name} wasn't born with the natural talents that some of his teammates were, but that hasn't held him back from being one of the key contributors to the ${team_nickname}. ${last_name} has been told his entire life that he would never be a professional baseball player and he's used that as fuel to prove those critics wrong. </p> <p>&quot;All my life, all I heard was that I couldn't do it,&quot; said ${last_name}.&quot;Well here I am.&quot;</p> <p>${last_name}'s scrappy style of play and fun-loving attitude has endeared him to teammates and fans alike. Fans go crazy whenever ${last_name} comes to bat and it's no surprise, whenever ${last_name} has a bat in his hand good things happen. </p> <p>Whenever a clutch hit or play is needed, ${last_name} is there to deliver it. He willingly sacrifices himself for the good of the team and puts 110 percent effort into everything he does on the field. That selflessness is not found in many professional baseball players anymore and is why he is the glue that holds the team together.</p><p>Grit, hustle, sacrifice, these things won't show up in the stats column, but are what a team needs to win. As a proven winner, ${last_name} just knows how to win. </p><p>When ${last_name} is given the opportunity he makes things happen and the ${team_nickname} would be wise to give him more opportunities in the future. ${last_name} doesn't complain about his lack of playing time though, he just gives it his all every time he has the chance. </p><p>&quot;If I have one at-bat or 1000 it doesn't matter, I'm going to do whatever it takes to get the team a win,&quot; ${last_name} said. &quot;I'm happy when the team is happy.&quot;</p><p>So while all the attention and praise is heaped on his more well-known teammates, ${last_name} will take comfort knowing that he has contributed in some small way to the team's success. </p></div>`;

    const story_2 = `<div id="story_content"><h1>${last_name} is looking for one last shot at a ring</h1>  <p>Among the rising stars and young prospects looking for their big break at ${team_full_name}'  Spring Training there will be one crafty veteran looking for one last shot at the World Series ring that has eluded him.</p> <p>${full_name} may not put up the stats that made him an All-Star anymore, but he can still be a valued  contributor, both on the field and in the clubhouse. ${last_name} will bring a veteran presence to the young team and can help teach the young guys a thing or two about how to play the game the right way. </p> <p>Few players have a better knowledge of the game than ${last_name} and it's that knowledge that has helped him transition gracefully into the twilight of his career. At an age when many players, even some of the best, falter, ${last_name} has thrived, using his wits and a little elbow grease to get the job done. </p> <p>&quot;The individual accolades are nice, but all I've wanted my entire career was a championship,&quot; said ${last_name}. &quot;This might be last chance to get one and I'll do whatever it takes to make sure the  ${team_nickname} are the ones celebrating in October.&quot;</p> <p>Signed to a short-term deal this offseason, ${last_name} isn't worried about the money &mdash; he has  plenty already &mdash; he just wants to win a title before he is forced to hang up his cleats for good.  He knows he doesn't have much time left in the Majors and he's determined to make the best of his last years  playing the game he loves.</p><p>Even if ${last_name}'s production isn't what it used to be, what he brings to  the ${team_nickname} can't be measured on a stat sheet. The young players on the  ${team_nickname} will benefit greatly from his calming influence during the long, grueling 162-game regular season. Just being around a guy like ${last_name} will raise his teammate's baseball IQ.</p> <p>&quot;I've been around the ballpark a few times,&quot; said ${last_name}. &quot;I definitely have a thing or  two I can teach these kids.&quot;</p><p>${last_name} will essentially be an extra coach out there, who can also play some ball. For this reason the move makes sense for the ${team_nickname}. While ${last_name}  wasn't the flashiest name out there this offseason, he will bring a toughness and mentality to the team that many players  couldn't. </p></div>`;

    const story_3 = `<div id="story_content"><h1>${last_name} just trying to fit in with ${team_nickname}</h1> <p>The ${team_full_name} made some noise this offseason when they signed ${full_name} to a huge free agent deal, one of the richest in the club's hiconst story. With the signing, the ${team_nickname} signaled to the baseball world that they weren't comfortable with the status quo. </p><p>For his part, ${last_name} is excited to join the ${team_nickname} and is ready to get acclimated with his new teammates at Spring Training. </p><p>&quot;I'm honored to be a member of a great organization like the ${team_full_name},&quot; said ${last_name}. &quot;They have some of the best fans in baseball and I can't wait to get out there and play for them.&quot;</p><p>When the ${team_nickname} announced the deal, many in the baseball world were shocked. While some have balked at the high price tag that came attached to ${last_name}, others say that this is the price the ${team_nickname} have to pay if they want to be competitive in today's Major League Baseball. </p><p>${last_name} is a bona fide star, there's no denying that. If he continues to play that way, the ${team_nickname} will be getting a bargain. <p>For those worried about how a free agent signing will affect the team's chemistry, they don't need to be concerned about ${last_name}. ${last_name} has been described as a model citizen by his former teammates and coaches and doesn't have the oversized personality that some All-Stars have, he will fit right in to the ${team_nickname}' family atmosphere. </p><p>&quot;I'm not here to ruffle feathers or make demands, I'm here to play baseball,&quot; said ${last_name}. &quot;My teammates are my brothers and I'll go out and fight for them every single night.&quot; </p><p>${last_name} is expected to contibute immediately to the ${team_nickname} and could be the difference maker the team was lacking during last season's campaign. While some free agents have struggled to perform after signing a big deal, there should be no concern that ${last_name} will have the same problems, he's a proven winner and competitor who will take on the challenge with ease. </p></div>`;
            
    const story_4 = `<div id="story_content"><h1>${team_nickname} confident ${last_name} will be worth the cost</h1><p>The ${team_full_name} made a splash when they traded for ${full_name} this offseason. ${last_name} will be expected to contribute immediately to the ${team_nickname} as they look to compete in the upcoming season. </p><p>${last_name} will meet his new teammates when Spring Training begins and will quickly have to adjust to an entirely new team and clubhouse. To his credit, ${last_name} has said that he will have no trouble becoming familiar with his new surroundings. </p><p>&quot;Baseball is a business and you have to be prepared to be thrown into an entirely new environment at a moment's notice,&quot; said ${last_name}. &quot;I'm just excited to be able to play for such a wonderful organization like the ${team_full_name} and in front of their awesome fans.&quot;</p><p>When the trade was first reported, many baseball observers were surprised. Most didn't know the ${team_nickname} were even in talks to acquire ${last_name}. ${last_name} himself said he was surprised by the news.</p><p>&quot;I was just driving home from dinner when I got a call saying that I was being traded to the ${team_nickname} and then minutes later it was all over the news,&quot; ${last_name} said.</p><p>Reaction to the trade has been mixed so far. While most people inside baseball recognize what ${last_name} will bring to the ${team_nickname}, they remain unconvinced that the ${team_nickname} didn't give up too much in return. </p><p>However, when you have the opportunity to acquire a player of ${last_name}'s caliber, you don't pass up that chance. This is a player who can contribute to the ${team_nickname} for years to come. He is a proven winner and makes things happen every time he steps on the diamond. </p><p>${last_name} isn't concerned with who won the trade, he's just concerned with winning games. </p><p>&quot;I don't care about the past,&quot; said ${last_name}. &quot;I'm on the ${team_nickname} now and that means my job is making sure the ${team_nickname} win some baseball games.&quot;</p></div>`;

    const story_5 = `<div id="story_content"><h1>${last_name} is ready to raise his game to the next level</h1><p>${full_name} is already a bona fide star for the ${team_full_name}, he's been an All-Star and one of the team's best players in recent years, but that doesn't mean he's done trying to improve. </p><p>${last_name} has been working out as hard as he can this offseason to be the best he can be this season. </p><p>&quot;I'm in the best shape of my life,&quot; said ${last_name}. &quot;I've been working hard every day, just trying to get bigger, faster, strong, just better all around.&quot;</p><p>While many players take the offseason to relax from the grueling regular season, ${last_name} refuses to take a break. The second the ${team_nickname}' season ended he was in the gym and working hard to improve his game; a work ethic rarely seen in a player of his caliber. </p><p>&quot;I don't know the meaning of quit,&quot; said ${last_name}. &quot;Everything I do, I do at maximum effort. My best is never good enough, I can always do better and I'm always working towards that.&quot;</p><p>But ${last_name} hasn't just spent all of his time in the gym and on the field, he's also been in the film room looking for that extra advantage.</p><p>&quot;I've watched all of my swings from last year, just breaking them down, picking out what went wrong so I can avoid the same mistakes this year,&quot; said ${last_name}. </p><p>The ${team_nickname} and their fans will get their first look at how all that hard work has paid off for ${last_name} at Spring Training. </p><p>Baseball is a game of inches and any little advantage can make the difference between a successful season and a failure. To see a star player like ${last_name} take that difference so seriously is refreshing and shows why he's one of the best players in the game already. That work ethic is what children today should be trying to imitate. </p><p>While some players might be in commercials or releasing their own brand of baseball equipment, ${last_name} is out there every day trying to be a better ballplayer. Fans of the ${team_nickname} are lucky to have such a humble star be a part of their team for years to come. </p></div>`;

    const story_6 = `<div id="story_content"><h1>${team_nickname} will have to get used to higher expectations</h1><p>The ${team_full_name} had a good year last season and with that success has come raised expectations heading into this year. Expectations which the ${team_nickname} players and coaches will have to deal with if they want to replicate or improve upon their success of last season.</p><p>The ${team_nickname} themselves are eager to prove that last year was no fluke and that they can play at such a high level for the years to come. With the right mix of stars and role players, they seem to be in good position to do so. </p><p>Many prognosticators have put out their preseason projections and the results are mixed for the ${team_nickname}. While projections are usually conservative, the ${team_nickname} are hoping they can beat their computer projected win total. They'll likely have to do so if they want to make the playoffs, even with the expanded Wild Card round. </p><p>As we all know, baseball isn't played in spreadsheets and while the projections are a fun what-if scenario for a rainy day, that's all they are. If the ${team_nickname} want to live up to the expectations that have been set for them, they will need to go out and play their best night in and night out. </p><p>Going into Spring Training everyone on the ${team_nickname} have been saying the right things, from the front office to the coaches to the players, but those are just words. Soon, the ${team_nickname} will have to put their money where their mouth is and produce on the field. </p><p>Many a team have been crushed under the pressure of raised expectations and the ${team_nickname} could be the next to fall victim. However, if all goes according to plan, fans will be in for a real treat when they watch the hometown team play.</p></div>`;

    const story_7 = `<div id="story_content"><h1>${team_nickname} ignoring critics who say they can't compete</h1><p>When preseason prognostications were being given by every publication under the sun this offseason, one team that was left consistently out of the playoff picture was the ${team_full_name}. The ${team_nickname} aren't going to let the critics get to them though, they know they can compete with the other teams in their division if given the chance and are confident they will be able to do so this year. </p><p>However, most projections have pegged the ${team_nickname} not only as a team on the outside of the playoff hunt, but also as a sure-to-be cellar dweller this season. But as we all know, the game of baseball isn't played on a spreadsheet, it's played on the field and the ${team_nickname} know that when they get out on the field they are just as good as any other team.</p><p>The ${team_nickname} will be united under one banner as they attempt to prove the world wrong and it all begins at Spring Training. Already players are flocking to the team's spring complex and practice grounds to start putting in the work needed to make their confidence a reality. </p><p>While they don't have the stars like some of the popular postseason picks, they have something that those teams don't: heart and the will to win. While stars will take a day off, this ${team_nickname} team won't, they'll grind out every game regardless of the score or their record at the time. With that kind of grit and determination it's hard not to believe that anything truly is possible for the ${team_nickname}.</p><p>While the favorites are walking around with a target on their backs, the ${team_nickname} are comfortable with flying under the radar. They know they will get the attention they deserve when they start proving themselves on the field. The ${team_nickname} are hoping they can turn some heads this season and show everyone why you should never count them out. </p><p>In any case, it's an exciting time to be a ${team_nickname} fan. The team camaraderie is infectious and it's hard not to feel like a part of their us against the world mentality.</p></div>`;

    const story_8 = `<div id="story_content"><h1>${team_nickname} looking to bounce back from last year's disappointment</h1><p>Last season the ${team_full_name} were expected to be one of the better teams in all of baseball. However, the team was unable to deliver on that promise and after an offseason dwelling on their failures they're ready to take another crack at it this year. </p><p>At the end of the season, the ${team_nickname} were counted among the biggest disappointments in Major League Baseball. The team didn't need the media or fans to tell them that though, they knew they had let both the fans and themselves down with their performance last year and are determined to rectify that this year. </p><p>Spring Training is right around the corner and with it comes a new season and a new opportunity to succeed. While many, both inside the game and out, have lowered their expectations for the ${team_nickname} after last season's disappointment, the team itself has not. They still think they can be one of the best teams in the game and they intend to prove it. </p><p>The team fell into the trap of reading their own press clippings too much and getting an inflated ego that prevented them from putting in the effort and determination required to be a winning baseball team. </p><p>But now the ${team_nickname} have learned their lesson and are much humbler entering this season. Ask any player, coach or front office personnel what their expectations are for the upcoming season and the answer is the same, we aren't going to make the same mistakes we did last season.</p><p>While many called for the front office to blow up the team and start over, the ${team_nickname} weren't convinced that they needed to take such drastic action. They know the talent that built up the expectations in the first place is still there and they think it's just a matter of more experience and effort that will bring the team success. </p><p>For that reason, the ${team_nickname} stayed quiet this offseason, just making a few minor moves here and there. While the spotlight shifted to other teams as they brought in marquee free agents, the ${team_nickname} became more and more anxious to prove to the baseball world why you don't count them out. The more people sleep on the ${team_nickname}, the more motivated they are to prove them wrong. ${team_nickname} fans everywhere hope they do.</p></div>`;

    const story_9 = `<div id="story_content"><h1>${last_name} to turn page on injury plagued year</h1><p>This time last year ${full_name} was getting ready for what he thought would be another full season playing the game he loved for the ${team_full_name}. The optimism of that spring quickly turned to dread though, as he suffered through a shortened campaign due to injuries.</p><p>After missing a large chunk of last season, ${last_name} is determined not to let that happen again. He has been spending all offseason working hard to get healthy and ready for a fresh start this season.</p><p>&quot;Last season was a huge disappointment,&quot; said ${last_name}. &quot;I hated having to sit out and watch my teammates play on TV, instead of being out there on the field with them.&quot;</p><p>The injury has served as motivation for ${last_name}. While many players were taking the offseason to relax and get away from the game, ${last_name} was doing the exact opposite as he tried to get back into playing shape. </p><p>&quot;I'm not going to let an injury hold me back from my goals,&quot; said ${last_name}. &quot;I've been working as hard as I can to get back to the player I know I am so I can help this team make it to the playoffs.&quot;</p><p>If anything, ${last_name} is more prepared coming into Spring Training this year than he has been at any time in his career. Some have said that he may be in the best shape of his life entering camp.</p><p>The ${team_nickname} and their fans will get their first look at how all that hard work has paid off for ${last_name} at Spring Training. After the troubles he went through last season, it will be a sight for sore eyes.</p><p>Baseball is a cruel mistress and sometimes even the best get cut down by the game. Last season was a disappointment for both ${last_name} and his fans, but he's worked hard to make sure hiconst story doesn't repeat itself this time.</p><p>The toughness ${last_name} has shown throughout his injury and rehab has been inspiring and goes to show that there are still some role models in this game for kids to look up to. Hopefully ${last_name} has his injury problems under control for years to come.</p></div>`;

    const story_10 = `<div id="story_content"><h1>Statistically Speaking: ${last_name} is due to regress</h1><p>Last year ${full_name} of the ${team_full_name} was one of the biggest surprises of the season. After barely winning a starting role, ${last_name} seized the opportunity and broke out in a big way.<p>This time last year, few if any would've guessed ${last_name} would be a star, both ZiPS and Steamer pegged him to be worth just a notch above replacement level. However, ${last_name} blew his projections out of the water and finished among the top players in the league in WAR according to FanGraphs. Last season was a huge success for ${last_name} and nobody can take that away from him, but there are still some questions about his future. While ${last_name} had excellent standard stats, his peripheral numbers showed some chinks in the armor.</p><p>To start, ${last_name} had a very abnormal batting average on balls in play. As we know, players have little control over their BABIPs and that number is likely due for some heavy regression back to the mean this coming season. Of course ${last_name}'s success wasn't entirely fueled by his BABIP, but that isn't the only concerning number. His strikeout rate and walk rate were both about league average, which is still good, but isn't best in the league good.</p><p>Taking all of those numbers into consideration, it's clear that ${last_name} benefited from a lot of good fortune last season. While he could still be a contibutor for the ${team_nickname}, that seems like a best case scenario and he isn't going to be close to being the superstar he appeared to be last year.</p></div>`;

    const story_11 = `<div id="story_content"><h1>Free Agent ${last_name} having personal Spring Training</h1><p>When ${full_name} became a free agent at the end of last season, it's safe to say he didn't anticipate still being a free agent when Spring Training rolled around. </p><p>&quot;Being a free agent this late in the year was not part of the plan,&quot; ${last_name} said. &quot;However, I've learned over the years that in baseball, things often don't go according to plan.&quot;</p><p>Yet here he is, after an offseason of wheeling and dealing still searching for the city he'll call his baseball home for at least the next year. Unlike his peers who are making their way to team complexes in Arizona or Florida, ${last_name} will be making his way down to the local high school field, where he will be having his own personal Spring Training. </p><p>&quot;I'm a baseball player and when the calendar turns to spring I start getting ready to play baseball again, whether I'm on a team or not,&quot; said ${last_name}. </p><p>While he certainly doesn't have all of the amenities one will find in Arizona or Florida, the most important thing remains, baseball. ${last_name} has put together his own training routine to keep his skills sharp, and he's out on the field every day at 8 AM like clockwork. </p><p>&quot;I just want to show teams that they don't have to worry about signing me so late in the process, I'll still be ready to play from day one,&quot; said ${last_name}. </p><p>And that's the kind of solid work ethic ${last_name} has displayed throughout his Major League career. While other players might take advantage of their extended offseason vacation, he's working harder than any player in the game. For him, each day brings a steady diet of drills, workouts and a hope that today's the day he learns who his new team will be. </p></div>`;

    const story_12 = `<div id="story_content"><h1>${last_name} turning heads at first Spring Training</h1><p>When the ${team_full_name} convened for the first of their annual Spring Training workouts there were a number of familiar faces and the typical stars and fan favorites were getting plenty of attention. However, there was one new face who was drawing his fair share of attention, top prospect ${full_name}. </p><p>While ${last_name} isn't expected to break camp with the Major League club, he's getting his feet wet in the low stakes fields of Spring Training, getting to know what will be expected of him soon. </p><p>&quot;I'm so excited to be here, part of a real Major League Spring Training, getting to feel like a real member of the ${team_nickname},&quot; said ${last_name}. &quot;This is what I've been dreaming about since I was a kid, being a real Major Leaguer.&quot;</p><p>That ${last_name} is expected to return to the minors for more seasoning hasn't tempered the expectations of fans, coaches or ${team_nickname} front office managers. </p><p>&quot;I'll be able to say I was there when ${last_name} first got his start, so that's pretty cool,&quot; said one fan walking away with a ${last_name} signed ball. </p><p>The future is certainly bright for ${last_name}, but right now he's just trying to soak it all in and make sure he makes a good first impression on his new teammates.</p><p>&quot;My focus right now is playing baseball and being one of the guys,&quot; said ${last_name}. &quot;I'm nothing special, these guys are the real Major Leaguers, I need to learn from them.&quot; </p><p>So far ${last_name} has shown a great attitude to go with his great talent and it isn't hard to imagine a time soon when he will be the star all the prospects are looking up to. For now though, fans and the team will have to be content with seeing a young player taking the next step in his journey to the majors. </p></div>`;

    const story_list = [story_1,story_2,story_3,story_4,story_5,story_6,story_7,story_8,story_9,story_10,story_11,story_12];
    return story_list[story_number];

}

function onStoryChange(){
    story_choice = buildStory(parseInt(story.value),team_full_name,full_name);
    try {
        story_node.removeChild(document.getElementById("story_content"));
    } catch(TypeError) {console.log(TypeError)}
    story_node.insertAdjacentHTML('beforeend', story_choice);
}

story.onchange = function(){onStoryChange()};

team_choice.onchange = function(){
    team_full_name = team_choice.options[team_choice.selectedIndex].text;
    fillPlayerChoice(parseInt(team_choice.value));
};

player_choice.onchange = function(){
    full_name = player_choice.options[player_choice.selectedIndex].text;
    if(story.value != ""){
        onStoryChange();
    }
}

document.getElementById('share').onclick = function() {
    var url = "https://jamesohara08.github.io/SpringTrainingStoryCreator?team_choice="+team_choice.value+"&player_choice="+player_choice.value.replace(" ","%20")+"&story_choice="+story.value;
     navigator.clipboard.writeText(url);
     alert("Copied the text: " + url);
}

window.addEventListener('load', checkURL);